In [3]:
import pandas as pd

url = 'https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv'
df = pd.read_csv(url)

In [3]:
df.shape

(10910, 26)

In [4]:
df.head()

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,...,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,...,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,...,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,...,NaN,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN

In [5]:
df.isna().sum()

Unnamed: 0                          0
Customer                            0
State                             631
Customer Lifetime Value             0
Response                          631
Coverage                            0
Education                           0
Effective To Date                   0
EmploymentStatus                    0
Gender                              0
Income                              0
Location Code                       0
Marital Status                      0
Monthly Premium Auto                0
Months Since Last Claim           633
Months Since Policy Inception       0
Number of Open Complaints         633
Number of Policies                  0
Policy Type                         0
Policy                              0
Renew Offer Type                    0
Sales Channel                       0
Total Claim Amount                  0
Vehicle Class                     622
Vehicle Size                      622
Vehicle Type                     5482
dtype: int64

In [4]:
df['Vehicle Type'].drop

<bound method Series.drop of 0        NaN
1        NaN
2          A
3          A
4        NaN
        ...
10905      A
10906      A
10907    NaN
10908      A
10909    NaN
Name: Vehicle Type, Length: 10910, dtype: object>

In [5]:
df = df.drop('Vehicle Type', axis=1)

In [10]:
df.head()

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,...,52,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,...,26,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,...,31,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,3,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,...,31,NaN,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize

In [12]:
df.sample(10)

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size
9274,9274,HV83672,Oregon,28393.329940,No,Extended,Bachelor,2/9/11,Employed,F,...,87,0.0,2,Personal Auto,Personal L1,Offer1,Branch,321.873474,Four-Door Car,Medsize
6109,6109,FB49203,California,6239.257541,No,Extended,College,2/26/11,Unemployed,F,...,63,0.0,3,Corporate Auto,Corporate L2,Offer1,Agent,655.200000,Two-Door Car,Medsize
7382,7382,NP88496,Nevada,20455.249460,No,Basic,High School or Below,1/5/11,Unemployed,F,...,72,0.0,2,Personal Auto,Personal L3,Offer3,Agent,482.400000,Four-Door Car,Large
2801,2801,XC32316,NaN,9657.579498,NaN,Extended,High School or Below,1/31/11,Unemployed,M,...,61,0.0,9,Corporate Auto,Corporate L1,Offer1,Agent,628.800000,SUV,Medsize
6272,6272,PD32052,California,7957.630101,No,Basic,High School or Below,1/19/11,Employed,M,...,67,NaN,2,Personal Auto,Personal L3,Offer1,Agent,430.291740,Four-Door Car,Medsize
2482,2482,EI17753,Oregon,4428.031583,Yes,Basic,High School or Below,1/29/11,Employed,F,...,62,0.0,1,Personal Auto,Personal L1,Offer1,Agent,303.872752,NaN,NaN
6455,6455,JS10224,California,18321.244710,No,Basic,College,2/16/11,Employed,F,...,26,0.0,2,Personal Auto,Personal L2,Offer2,Branch,10.367410,Four-Door Car,Medsize
2870,2870,DP50922,NaN,12663.990570,NaN,Basic,High School or Below,2/5/11,Employed,M,...,34,NaN,2,Personal Auto,Personal L3,Offer2,Web,504.000000,Sports Car,Medsize
3950,3950,VW70435,Oregon,4929.549699,Yes,Basic,Bachelor,1/26/11,Employed,M,...,52,0.0,7,Personal Auto,Personal L3,Offer2,Call Center,351.270869,Two-Door Car,Medsize
7752,7752,VH31071,Arizona,9256.918609,No,Basic,College,1/19/11,Disabled,F,...,76,0.0,9,Personal Auto,Personal L3,Offer1,Call Center,566.400000,SUV,Large

In [6]:
VehicleClass_mode = df['Vehicle Class'].mode()[0]
df['Vehicle Class'] = df['Vehicle Class'].fillna(VehicleClass_mode)

In [15]:
df.head()

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,...,52,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,...,26,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,...,31,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,3,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,...,31,NaN,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize

In [16]:
df.isna().sum()

Unnamed: 0                         0
Customer                           0
State                            631
Customer Lifetime Value            0
Response                         631
Coverage                           0
Education                          0
Effective To Date                  0
EmploymentStatus                   0
Gender                             0
Income                             0
Location Code                      0
Marital Status                     0
Monthly Premium Auto               0
Months Since Last Claim          633
Months Since Policy Inception      0
Number of Open Complaints        633
Number of Policies                 0
Policy Type                        0
Policy                             0
Renew Offer Type                   0
Sales Channel                      0
Total Claim Amount                 0
Vehicle Class                      0
Vehicle Size                     622
dtype: int64

In [7]:
df['Response'] = df['Response'].fillna('No')

In [18]:
df.isna().sum()

Unnamed: 0                         0
Customer                           0
State                            631
Customer Lifetime Value            0
Response                           0
Coverage                           0
Education                          0
Effective To Date                  0
EmploymentStatus                   0
Gender                             0
Income                             0
Location Code                      0
Marital Status                     0
Monthly Premium Auto               0
Months Since Last Claim          633
Months Since Policy Inception      0
Number of Open Complaints        633
Number of Policies                 0
Policy Type                        0
Policy                             0
Renew Offer Type                   0
Sales Channel                      0
Total Claim Amount                 0
Vehicle Class                      0
Vehicle Size                     622
dtype: int64

In [8]:
pd.set_option('display.max_columns', None)
df.sample(20)

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Income,Location Code,Marital Status,Monthly Premium Auto,Months Since Last Claim,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size
5346,5346,LH26131,Nevada,3876.772694,No,Premium,High School or Below,2/8/11,Unemployed,F,0,Suburban,Single,108,2.0,18,0.0,1,Personal Auto,Personal L2,Offer1,Agent,1099.233361,Two-Door Car,Large
7282,7282,ZZ54454,Nevada,4589.940596,No,Premium,Master,1/10/11,Employed,M,32510,Suburban,Single,119,29.0,38,0.0,1,Personal Auto,Personal L2,Offer2,Agent,571.200000,Two-Door Car,Small
718,718,KW95891,Oregon,2635.148447,No,Basic,High School or Below,1/28/11,Employed,F,93884,Suburban,Married,65,7.0,10,0.0,1,Personal Auto,Personal L3,Offer4,Branch,312.000000,Four-Door Car,NaN
2676,2676,UV49359,Nevada,7372.230729,No,Basic,Bachelor,1/24/11,Employed,F,74335,Urban,Single,187,3.0,4,0.0,1,Corporate Auto,Corporate L1,Offer3,Agent,896.436023,Luxury Car,Small
8696,8696,GC36679,Oregon,3305.129877,No,Extended,High School or Below,1/25/11,Employed,M,40778,Suburban,Single,86,1.0,59,0.0,1,Personal Auto,Personal L3,Offer2,Web,412.800000,Four-Door Car,Medsize
3143,3143,BK15048,Arizona,6656.709233,No,Basic,College,1/20/11,Unemployed,M,0,Suburban,Single,69,23.0,32,1.0,2,Personal Auto,Personal L3,Offer1,Branch,496.800000,Four-Door Car,Small
3590,3590,GE63585,NaN,2420.711888,No,Basic,Bachelor,2/7/11,Employed,M,31710,Urban,Divorced,62,5.0,29,0.0,1,Corporate Auto,Corporate L3,Offer1,Call Center,199.551735,Two-Door Car,Medsize
3605,3605,XI16714,Arizona,2554.032052,No,Basic,High School or Below,2/19/11,Unemployed,F,0,Suburban,Single,72,32.0,14,0.0,1,Corporate Auto,Corporate L1,Offer4,Web,405.804184,Four-Door Car,Medsize
5530,5530,NC68853,Oregon,11293.981920,No,Basic,High School or Below,1/15/11,Unemployed,M,0,Suburban,Married,104,19.0,32,0.0,2,Personal Auto,Personal L3,Offer1,Call Center,499.200000,SUV,Medsize
3956,3956,HK28125,California,24337.381810,No,Extended,High School or Below,1/4/11,Unemployed,M,0,Suburban,Single,85,5.0,15,1.0,2,Personal Auto,Personal L2,Offer2,Agent,612.000000,Four-Door Car,Medsize
5753,5753,TP51897,California,2621.808611,No,Basic,College,2/20/11,Employed,F,36843,Suburban,Married,68,12.0,11,3.0,1,Corporate Auto,Corporate L1,Offer4,Agent,357.642982,Four-Door Car,Medsize
9135,9135,MY56715,Oregon,3380.712383,No,Extended,Bachelor,2/27/11,Employed,M,58109,Suburban,Divorced,86,9.0,6,0.0,1,Corporate Auto,Corporate L3,Offer2,Branch,412.800000,Two-Door Car,Medsize
1975,1975,GK13851,Oregon,9227.567263,No,Extended,College,1/24/11,Unemployed,M,0,Suburban,Single,129,15.0,42,0.0,3,Personal Auto,Personal L1,Offer3,Call Center,619.200000,SUV,Medsize
6767,6767,ZE85014,California,2357.747015,No,Basic,College,1/20/11,Disabled,M,25064,Suburban,Married,62,17.0,34,0.0,1,Personal Auto,Personal L3,Offer1,Call Center,297.600000,Four-Door Car,Medsize
3212,3212,AB26022,Oregon,7998.347343,No,Basic,High School or Below,1/10/11,Retired,M,26487,Suburban,Single,112,NaN,82,NaN,3,Corporate Auto,Corporate L2,Offer1,Call Center,602.431489,SUV,Medsize
6450,6450,ZA44520,Arizona,9621.726190,No,Extended,High School or Below,2/10/11,Employed,F,54872,Suburban,Married,121,9.0,50,0.0,3,Personal Auto,Personal L3,Offer2,Agent,580.800000,SUV,Large
10125,10125,XZ54522,Nevada,8810.895550,No,Premium,Bachelor,2/25/11,Employed,F,76266,Rural,Single,110,24.0,88,1.0,3,Personal Auto,Personal L1,Offer1,Branch,155.708627,Two-Door Car,Medsize
4434,4434,UZ42802,Oregon,4526.606038,No,Extended,Bachelor,2/6/11,Unemployed,M,0,Suburban,Single,135,28.0,66,0.0,1,Personal Auto,Personal L3,Offer1,Agent,1516.383753,Sports Car,Large
7484,7484,IZ47097,Arizona,2927.216278,No,Basic,Master,2/3/11,Employed,F,76850,Suburban,Married,72,NaN,84,NaN,1,Personal Auto,Personal L3,Offer1,Agent,345.600000,Four-Door Car,Medsize
2923,2923,TU64352,Oregon,4078.023331,No,Basic,College,1/7/11,Unemployed,F,0,Suburban,Single,116,18.0,86,0.0,1,Personal Auto,Personal L1,Offer1,Agent,835.200000,Sports Car,Medsize

In [9]:
state_mode = df['State'].mode()[0]
df['State'] = df['State'].fillna(state_mode)

# Fill specific numerical columns with zero if that makes sense
df['Months Since Last Claim'] = df['Months Since Last Claim'].fillna(0)
df['Number of Open Complaints'] = df['Number of Open Complaints'].fillna(0)

# Fill 'Vehicle Size' with its mode
vehicle_size_mode = df['Vehicle Size'].mode()[0]
df['Vehicle Size'] = df['Vehicle Size'].fillna(vehicle_size_mode)

In [27]:
df.isna().sum()

Unnamed: 0                       0
Customer                         0
State                            0
Customer Lifetime Value          0
Response                         0
Coverage                         0
Education                        0
Effective To Date                0
EmploymentStatus                 0
Gender                           0
Income                           0
Location Code                    0
Marital Status                   0
Monthly Premium Auto             0
Months Since Last Claim          0
Months Since Policy Inception    0
Number of Open Complaints        0
Number of Policies               0
Policy Type                      0
Policy                           0
Renew Offer Type                 0
Sales Channel                    0
Total Claim Amount               0
Vehicle Class                    0
Vehicle Size                     0
dtype: int64

In [28]:
df.head()

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Income,Location Code,Marital Status,Monthly Premium Auto,Months Since Last Claim,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,48029,Suburban,Married,61,7.0,52,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,0,Suburban,Single,64,3.0,26,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,22139,Suburban,Single,100,34.0,31,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,49078,Suburban,Single,97,10.0,3,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,23675,Suburban,Married,117,0.0,31,0.0,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize

In [10]:
filtered_df = df[(df['Total Claim Amount'] < 1000) & (df['Response'] == 'Yes')]

In [31]:
filtered_df.tail()

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Income,Location Code,Marital Status,Monthly Premium Auto,Months Since Last Claim,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size
10844,10844,FM31768,Arizona,5979.724161,Yes,Extended,High School or Below,2/7/11,Employed,F,57693,Suburban,Divorced,76,16.0,56,0.0,3,Personal Auto,Personal L1,Offer2,Agent,547.200000,Four-Door Car,Medsize
10852,10852,KZ80424,Washington,8382.478392,Yes,Basic,Bachelor,1/27/11,Employed,M,25998,Suburban,Married,71,16.0,38,0.0,2,Personal Auto,Personal L2,Offer2,Call Center,791.878042,Four-Door Car,Medsize
10872,10872,XT67997,California,5979.724161,Yes,Extended,High School or Below,2/7/11,Employed,F,57693,Suburban,Divorced,76,16.0,56,0.0,3,Personal Auto,Personal L3,Offer2,Agent,547.200000,Four-Door Car,Medsize
10887,10887,BY78730,Oregon,8879.790017,Yes,Basic,High School or Below,2/3/11,Employed,F,52583,Urban,Single,113,12.0,59,0.0,7,Special Auto,Special L2,Offer1,Agent,528.200860,SUV,Small
10897,10897,MM70762,Arizona,9075.768214,Yes,Basic,Master,1/26/11,Employed,M,37722,Rural,Single,116,8.0,23,0.0,8,Personal Auto,Personal L1,Offer1,Agent,158.077504,Sports Car,Medsize

In [11]:
filtered_df = df[(df['Response'] == 'Yes')]

In [33]:
pivot_df = filtered_df.pivot_table(index='Policy Type', columns='Gender', values='Monthly Premium Auto', aggfunc='mean')

In [36]:
pivot_df

Gender                  F          M
Policy Type
Corporate Auto  94.301775  92.188312
Personal Auto   98.998148  91.085821
Special Auto    92.314286  86.343750

In [13]:
filtered_df.groupby(['Gender', 'Policy Type']).agg({
    'Monthly Premium Auto': 'mean',  # Mean of Age
    'Total Claim Amount': 'sum'  # Total of Total Claim Amount
})

                       Monthly Premium Auto  Total Claim Amount
Gender Policy Type
F      Corporate Auto             94.301775        73301.806356
       Personal Auto              98.998148       244601.601493
       Special Auto               92.314286        15864.805731
M      Corporate Auto             92.188312        62921.698760
       Personal Auto              91.085821       244957.455290
       Special Auto               86.343750        13744.894135

In [14]:
df.groupby('State')['Customer'].count()

State
Arizona       1937
California    4183
Nevada         993
Oregon        2909
Washington     888
Name: Customer, dtype: int64

In [20]:
df.sample(10)

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Income,Location Code,Marital Status,Monthly Premium Auto,Months Since Last Claim,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size
9496,9496,BV12771,California,27420.813180,No,Basic,College,2/27/11,Unemployed,M,0,Suburban,Married,112,23.0,20,0.0,2,Personal Auto,Personal L2,Offer3,Branch,537.600000,SUV,Medsize
4073,4073,GY40926,California,2612.528734,No,Basic,College,1/26/11,Employed,M,37073,Suburban,Married,66,16.0,35,0.0,1,Personal Auto,Personal L3,Offer2,Branch,316.800000,Four-Door Car,Medsize
9967,9967,ZJ27465,California,14137.230430,No,Basic,College,2/18/11,Employed,F,31794,Suburban,Divorced,119,12.0,16,0.0,2,Personal Auto,Personal L3,Offer1,Agent,571.200000,SUV,Medsize
7323,7323,FN61865,Nevada,4271.200049,No,Premium,Master,2/6/11,Employed,F,26245,Rural,Single,110,6.0,43,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,44.284642,Two-Door Car,Medsize
1659,1659,SR24177,Nevada,5763.265424,No,Extended,Bachelor,2/10/11,Employed,M,31725,Rural,Single,76,31.0,9,0.0,5,Personal Auto,Personal L2,Offer1,Agent,177.234000,Two-Door Car,Medsize
1138,1138,WR86431,Nevada,10883.787850,No,Extended,High School or Below,1/25/11,Employed,F,91123,Rural,Divorced,138,32.0,70,3.0,8,Corporate Auto,Corporate L1,Offer1,Agent,103.462381,SUV,Medsize
1580,1580,AF81450,California,11431.730890,No,Basic,High School or Below,1/26/11,Disabled,M,28657,Suburban,Married,100,4.0,55,0.0,2,Personal Auto,Personal L3,Offer1,Branch,588.742251,SUV,Small
2813,2813,CI95726,Nevada,3644.833554,Yes,Extended,High School or Below,1/15/11,Employed,F,82477,Suburban,Married,90,1.0,69,0.0,1,Personal Auto,Personal L3,Offer2,Agent,432.000000,Two-Door Car,Large
9024,9024,UD20999,California,2537.667511,No,Basic,Master,2/22/11,Unemployed,M,0,Suburban,Married,68,32.0,28,0.0,1,Corporate Auto,Corporate L3,Offer2,Branch,326.400000,Four-Door Car,Medsize
2703,2703,WC22220,Arizona,2616.613903,Yes,Basic,College,2/25/11,Employed,M,72302,Suburban,Divorced,66,6.0,27,0.0,1,Corporate Auto,Corporate L2,Offer1,Agent,316.800000,Two-Door Car,Medsize

In [22]:
state_counts = df.groupby('State').size()

# Filter states with more than 500 customers
filtered_states = state_counts[state_counts > 500]

# Print the result
print(filtered_states)

State
Arizona       1937
California    4183
Nevada         993
Oregon        2909
Washington     888
dtype: int64

In [23]:
df.groupby(['Gender', 'Education'])['Customer Lifetime Value'].agg(['max', 'min', 'median'])

                                     max          min       median
Gender Education
F      Bachelor              73225.95652  1904.000852  5640.505303
       College               61850.18803  1898.683686  5623.611187
       Doctor                44856.11397  2395.570000  5332.462694
       High School or Below  55277.44589  2144.921535  6039.553187
       Master                51016.06704  2417.777032  5729.855012
M      Bachelor              67907.27050  1898.007675  5548.031892
       College               61134.68307  1918.119700  6005.847375
       Doctor                32677.34284  2267.604038  5577.669457
       High School or Below  83325.38119  1940.981221  6286.731006
       Master                50568.25912  2272.307310  5579.099207