In [39]:
import pandas as pd
import numpy as np

In [51]:
url = 'https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv'
df = pd.read_csv(url)
url1 = 'https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv'
df1 = pd.read_csv(url1)
url2 = 'https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv'
df2 = pd.read_csv(url2)

In [52]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   1071 non-null   object
 1   ST                         1071 non-null   object
 2   GENDER                     954 non-null    object
 3   Education                  1071 non-null   object
 4   Customer Lifetime Value    1068 non-null   object
 5   Income                     1071 non-null   float64
 6   Monthly Premium Auto       1071 non-null   float64
 7   Number of Open Complaints  1071 non-null   object
 8   Policy Type                1071 non-null   object
 9   Vehicle Class              1071 non-null   object
 10  Total Claim Amount         1071 non-null   float64
dtypes: float64(3), object(8)
memory usage: 344.6+ KB
None

In [4]:
df.shape

(4008, 11)

In [5]:
df.head

<bound method NDFrame.head of      Customer          ST GENDER             Education  \
0     RB50392  Washington    NaN                Master
1     QZ44356     Arizona      F              Bachelor
2     AI49188      Nevada      F              Bachelor
3     WW63253  California      M              Bachelor
4     GA49547  Washington      M  High School or Below
...       ...         ...    ...                   ...
4003      NaN         NaN    NaN                   NaN
4004      NaN         NaN    NaN                   NaN
4005      NaN         NaN    NaN                   NaN
4006      NaN         NaN    NaN                   NaN
4007      NaN         NaN    NaN                   NaN

     Customer Lifetime Value   Income  Monthly Premium Auto  \
0                        NaN      0.0                1000.0
1                 697953.59%      0.0                  94.0
2                1288743.17%  48767.0                 108.0
3                 764586.18%      0.0                 106.0
4                 536307.65%  36357.0                  68.0
...                      ...      ...                   ...
4003                     NaN      NaN                   NaN
4004                     NaN      NaN                   NaN
4005                     NaN      NaN                   NaN
4006                     NaN      NaN                   NaN
4007                     NaN      NaN                   NaN

     Number of Open Complaints     Policy Type  Vehicle Class  \
0                       1/0/00   Personal Auto  Four-Door Car
1                       1/0/00   Personal Auto  Four-Door Car
2                       1/0/00   Personal Auto   Two-Door Car
3                       1/0/00  Corporate Auto            SUV
4                       1/0/00   Personal Auto  Four-Door Car
...                        ...             ...            ...
4003                       NaN             NaN            NaN
4004                       NaN             NaN            NaN
4005                       NaN             NaN            NaN
4006                       NaN             NaN            NaN
4007                       NaN             NaN            NaN

      Total Claim Amount
0               2.704934
1            1131.464935
2             566.472247
3             529.881344
4              17.269323
...                  ...
4003                 NaN
4004                 NaN
4005                 NaN
4006                 NaN
4007                 NaN

[4008 rows x 11 columns]>

In [10]:
df1.head

<bound method NDFrame.head of     Customer          ST GENDER Education Customer Lifetime Value  Income  \
0    GS98873     Arizona      F  Bachelor              323912.47%   16061
1    CW49887  California      F    Master              462680.11%   79487
2    MY31220  California      F   College              899704.02%   54230
3    UH35128      Oregon      F   College             2580706.30%   71210
4    WH52799     Arizona      F   College              380812.21%   94903
..       ...         ...    ...       ...                     ...     ...
991  HV85198     Arizona      M    Master              847141.75%   63513
992  BS91566     Arizona      F   College              543121.91%   58161
993  IL40123      Nevada      F   College              568964.41%   83640
994  MY32149  California      F    Master              368672.38%       0
995  SA91515  California      M  Bachelor              399258.39%       0

     Monthly Premium Auto Number of Open Complaints  Total Claim Amount  \
0                      88                    1/0/00          633.600000
1                     114                    1/0/00          547.200000
2                     112                    1/0/00          537.600000
3                     214                    1/1/00         1027.200000
4                      94                    1/0/00          451.200000
..                    ...                       ...                 ...
991                    70                    1/0/00          185.667213
992                    68                    1/0/00          140.747286
993                    70                    1/0/00          471.050488
994                    96                    1/0/00           28.460568
995                   111                    1/0/00          700.349052

        Policy Type  Vehicle Class
0     Personal Auto  Four-Door Car
1      Special Auto            SUV
2     Personal Auto   Two-Door Car
3     Personal Auto     Luxury Car
4    Corporate Auto   Two-Door Car
..              ...            ...
991   Personal Auto  Four-Door Car
992  Corporate Auto  Four-Door Car
993  Corporate Auto   Two-Door Car
994   Personal Auto   Two-Door Car
995   Personal Auto            SUV

[996 rows x 11 columns]>

In [13]:
df2.head

<bound method NDFrame.head of     Customer          ST GENDER Education Customer Lifetime Value  Income  \
0    GS98873     Arizona      F  Bachelor              323912.47%   16061
1    CW49887  California      F    Master              462680.11%   79487
2    MY31220  California      F   College              899704.02%   54230
3    UH35128      Oregon      F   College             2580706.30%   71210
4    WH52799     Arizona      F   College              380812.21%   94903
..       ...         ...    ...       ...                     ...     ...
991  HV85198     Arizona      M    Master              847141.75%   63513
992  BS91566     Arizona      F   College              543121.91%   58161
993  IL40123      Nevada      F   College              568964.41%   83640
994  MY32149  California      F    Master              368672.38%       0
995  SA91515  California      M  Bachelor              399258.39%       0

     Monthly Premium Auto Number of Open Complaints  Total Claim Amount  \
0                      88                    1/0/00          633.600000
1                     114                    1/0/00          547.200000
2                     112                    1/0/00          537.600000
3                     214                    1/1/00         1027.200000
4                      94                    1/0/00          451.200000
..                    ...                       ...                 ...
991                    70                    1/0/00          185.667213
992                    68                    1/0/00          140.747286
993                    70                    1/0/00          471.050488
994                    96                    1/0/00           28.460568
995                   111                    1/0/00          700.349052

        Policy Type  Vehicle Class
0     Personal Auto  Four-Door Car
1      Special Auto            SUV
2     Personal Auto   Two-Door Car
3     Personal Auto     Luxury Car
4    Corporate Auto   Two-Door Car
..              ...            ...
991   Personal Auto  Four-Door Car
992  Corporate Auto  Four-Door Car
993  Corporate Auto   Two-Door Car
994   Personal Auto   Two-Door Car
995   Personal Auto            SUV

[996 rows x 11 columns]>

In [53]:
df_c= pd.concat([df, df1,df2], axis=0)

In [16]:
df_c.shape

(6000, 11)

In [54]:
df_c = df_c.drop_duplicates()

In [18]:
df_c.shape

(2065, 11)

In [19]:
df_c.info

<bound method DataFrame.info of     Customer          ST GENDER             Education Customer Lifetime Value  \
0    RB50392  Washington    NaN                Master                     NaN
1    QZ44356     Arizona      F              Bachelor              697953.59%
2    AI49188      Nevada      F              Bachelor             1288743.17%
3    WW63253  California      M              Bachelor              764586.18%
4    GA49547  Washington      M  High School or Below              536307.65%
..       ...         ...    ...                   ...                     ...
991  HV85198     Arizona      M                Master              847141.75%
992  BS91566     Arizona      F               College              543121.91%
993  IL40123      Nevada      F               College              568964.41%
994  MY32149  California      F                Master              368672.38%
995  SA91515  California      M              Bachelor              399258.39%

      Income  Monthly Premium Auto Number of Open Complaints     Policy Type  \
0        0.0                1000.0                    1/0/00   Personal Auto
1        0.0                  94.0                    1/0/00   Personal Auto
2    48767.0                 108.0                    1/0/00   Personal Auto
3        0.0                 106.0                    1/0/00  Corporate Auto
4    36357.0                  68.0                    1/0/00   Personal Auto
..       ...                   ...                       ...             ...
991  63513.0                  70.0                    1/0/00   Personal Auto
992  58161.0                  68.0                    1/0/00  Corporate Auto
993  83640.0                  70.0                    1/0/00  Corporate Auto
994      0.0                  96.0                    1/0/00   Personal Auto
995      0.0                 111.0                    1/0/00   Personal Auto

     Vehicle Class  Total Claim Amount
0    Four-Door Car            2.704934
1    Four-Door Car         1131.464935
2     Two-Door Car          566.472247
3              SUV          529.881344
4    Four-Door Car           17.269323
..             ...                 ...
991  Four-Door Car          185.667213
992  Four-Door Car          140.747286
993   Two-Door Car          471.050488
994   Two-Door Car           28.460568
995            SUV          700.349052

[2065 rows x 11 columns]>

In [23]:
df_c.describe()

             Income  Monthly Premium Auto  Total Claim Amount
count   2064.000000           2064.000000         2064.000000
mean   39506.675872            169.289729          410.833935
std    30338.414847           1219.971732          283.192990
min        0.000000             61.000000            0.382107
25%    15162.750000             68.000000          245.354739
50%    36509.000000             81.000000          350.400000
75%    64289.500000            108.000000          523.815839
max    99981.000000          35354.000000         2893.239678

In [43]:
df_c.isnull().sum()

Customer                       1
ST                             1
GENDER                       123
Education                      1
Customer Lifetime Value        8
Income                         1
Monthly Premium Auto           1
Number of Open Complaints      1
Policy Type                    1
Vehicle Class                  1
Total Claim Amount             1
dtype: int64

In [27]:
df_c.GENDER.unique()

array([nan, 'F', 'M', 'Femal', 'Male', 'female'], dtype=object)

In [44]:
df_c['GENDER']=df_c['GENDER'].replace({'Male':'M', 'Femal':'F', 'female':'F' })

In [45]:
df_c.GENDER.unique()

array([nan, 'F', 'M'], dtype=object)

In [46]:
df_c.isnull().sum()

Customer                       1
ST                             1
GENDER                       123
Education                      1
Customer Lifetime Value        8
Income                         1
Monthly Premium Auto           1
Number of Open Complaints      1
Policy Type                    1
Vehicle Class                  1
Total Claim Amount             1
dtype: int64

In [55]:
gender_mode = df_c['GENDER'].mode()[0]

# Fill null values in the GENDER column with the mode
df_c['GENDER'] = df_c['GENDER'].fillna(gender_mode)

In [56]:
df_c.isnull().sum()

Customer                     1
ST                           1
GENDER                       0
Education                    1
Customer Lifetime Value      8
Income                       1
Monthly Premium Auto         1
Number of Open Complaints    1
Policy Type                  1
Vehicle Class                1
Total Claim Amount           1
dtype: int64

In [60]:
df_c= df_c.dropna()

In [61]:
df_c.isnull().sum()

Customer                     0
ST                           0
GENDER                       0
Education                    0
Customer Lifetime Value      0
Income                       0
Monthly Premium Auto         0
Number of Open Complaints    0
Policy Type                  0
Vehicle Class                0
Total Claim Amount           0
dtype: int64

In [66]:
url3 = 'https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv'
mkt = pd.read_csv(url3)

In [67]:
mkt.shape

(10910, 27)

In [68]:
mkt.head()

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,A,2
1,1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,A,1
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,2
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,A,1

In [69]:
df_c.columns = df_c.columns.str.lower()

In [72]:
df_c.shape

(2057, 11)

In [73]:
df_c.columns = df_c.columns.str.replace(' ', '_')

In [74]:
df_c.head()

,customer,st,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
5,OC83172,Oregon,F,Bachelor,825629.78%,62902.0,69.0,1/0/00,Personal Auto,Two-Door Car,159.383042

In [75]:
mkt.head()

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,A,2
1,1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,A,1
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,2
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,A,1

In [77]:
df_c.rename(columns={'st': 'state'}, inplace=True)

In [79]:
df_c.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
5,OC83172,Oregon,F,Bachelor,825629.78%,62902.0,69.0,1/0/00,Personal Auto,Two-Door Car,159.383042

In [80]:
mkt.isnull().sum()

unnamed:_0                       0
customer                         0
state                            0
customer_lifetime_value          0
response                         0
coverage                         0
education                        0
effective_to_date                0
employmentstatus                 0
gender                           0
income                           0
location_code                    0
marital_status                   0
monthly_premium_auto             0
months_since_last_claim          0
months_since_policy_inception    0
number_of_open_complaints        0
number_of_policies               0
policy_type                      0
policy                           0
renew_offer_type                 0
sales_channel                    0
total_claim_amount               0
vehicle_class                    0
vehicle_size                     0
vehicle_type                     0
month                            0
dtype: int64

In [81]:
mkt.tail()

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
10905,10905,FE99816,Nevada,15563.369440,No,Premium,Bachelor,2011-01-19,Unemployed,F,...,7,Personal Auto,Personal L1,Offer3,Web,1214.400000,Luxury Car,Medsize,A,1
10906,10906,KX53892,Oregon,5259.444853,No,Basic,College,2011-01-06,Employed,F,...,6,Personal Auto,Personal L3,Offer2,Branch,273.018929,Four-Door Car,Medsize,A,1
10907,10907,TL39050,Arizona,23893.304100,No,Extended,Bachelor,2011-02-06,Employed,F,...,2,Corporate Auto,Corporate L3,Offer1,Web,381.306996,Luxury SUV,Medsize,A,2
10908,10908,WA60547,California,11971.977650,No,Premium,College,2011-02-13,Employed,F,...,6,Personal Auto,Personal L1,Offer1,Branch,618.288849,SUV,Medsize,A,2
10909,10909,IV32877,California,6857.519928,No,Basic,Bachelor,2011-01-08,Unemployed,M,...,3,Personal Auto,Personal L1,Offer4,Web,1021.719397,SUV,Medsize,A,1

In [82]:
mkt.gender.unique()

array(['M', 'F'], dtype=object)

In [87]:
pivot_mkt = mkt.pivot_table( columns='sales_channel', values=['total_claim_amount'], aggfunc='sum').round(2)

In [88]:
pivot_mkt

sales_channel            Agent     Branch  Call Center        Web
total_claim_amount  1810226.82  1301204.0    926600.82  706600.04

In [89]:
pivot_mkt = mkt.pivot_table( columns='education', values=['customer_lifetime_value'], aggfunc='sum')

In [90]:
pivot_mkt

education,Bachelor,College,Doctor,High School or Below,Master
customer_lifetime_value,2.549632e+07,2.531183e+07,2.956184e+06,2.647451e+07,7.240159e+06